apiVersion: v1
kind: Service
metadata:
  name: cistafirma-backend
  namespace: cistafirma
spec:
  selector:
    app: cistafirma-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000

