apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cistafirma-ingress
  namespace: cistafirma
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: cistafirma.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cistafirma-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cistafirma-frontend
                port:
                  number: 80

