# Generated by Django 5.2.8 on 2026-07-25 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('companies', '0008_add_uses_ifrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_stack', models.JSONField(blank=True, default=list,
                                                help_text='Inferovaný tech stack (jazyky, frameworky, tools)',
                                                verbose_name='Technologický základ')),
                ('company_summary',
                 models.TextField(blank=True, default='', help_text='Gpt-4-generated business summary (SK)',
                                  verbose_name='Zhrnutie firmy')),
                ('outreach_angle',
                 models.TextField(blank=True, default='', help_text='Personalizovaný návrh na kontaktovanie',
                                  verbose_name='Uhol pre kontaktovanie')),
                ('outreach_draft', models.TextField(blank=True, default='', help_text='Návrh otváracej správy (SK)',
                                                    verbose_name='Návrh správy')),
                ('sources_used',
                 models.JSONField(blank=True, default=list, help_text='Zoznam zdrojov, z ktorých pochádza obohacenie',
                                  verbose_name='Použité zdroje')),
                ('confidence_score',
                 models.PositiveIntegerField(default=50, help_text='Stupeň spoľahlivosti AI obohacenia (0-100)',
                                             verbose_name='Spoľahlivosť')),
                ('enriched_at', models.DateTimeField(auto_now_add=True, verbose_name='Obohacené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment',
                                                 to='companies.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Obohacenie firmy',
                'verbose_name_plural': 'Obohacenie firiem',
                'ordering': ['-confidence_score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text='Výsledné skóre od 0 do 100',
                                                      verbose_name='Celkové skóre')),
                ('nace_relevance_score',
                 models.PositiveIntegerField(default=0, help_text='Skóre za zhodnosť s cieľovým SK NACE (0-40)',
                                             verbose_name='SK NACE relevancia')),
                ('data_completeness_score',
                 models.PositiveIntegerField(default=0, help_text='Skóre za dostupnosť ORSR, financií, VšZP (0-30)',
                                             verbose_name='Úplnosť údajov')),
                ('financial_health_score',
                 models.PositiveIntegerField(default=0, help_text='Skóre za absenciu dlhov a pozitívnu dynamiku (0-30)',
                                             verbose_name='Finančné zdravie')),
                ('debt_penalty',
                 models.IntegerField(default=0, help_text='Penalizácia za prítomnosť dlhov (0 alebo negatívny)',
                                     verbose_name='Penalizácia za dlhy')),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Detailný rozpad signálov a bodov',
                                               verbose_name='Detailný rozpad')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Vypočítané')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_score',
                                                 to='companies.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Skóre firmy',
                'verbose_name_plural': 'Skóre firiem',
                'ordering': ['-score', '-updated_at'],
                'indexes': [models.Index(fields=['-score'], name='lead_scorin_score_22b2ab_idx'),
                            models.Index(fields=['-updated_at'], name='lead_scorin_updated_f9fd57_idx')],
            },
        ),
    ]
