# Generated by Django 6.0.1 on 2026-05-31 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Emailové notifikácie')),
                ('on_debt_change', models.BooleanField(default=True, help_text='Nový dlh alebo zmena výšky dlhu voči VšZP, SP, FS', verbose_name='Zmena dlhov')),
                ('on_status_change', models.BooleanField(default=True, help_text='Zrušenie, likvidácia, konkurz', verbose_name='Zmena statusu firmy')),
                ('on_executive_change', models.BooleanField(default=False, help_text='Nový konateľ, prokurista, zmena v orgánoch', verbose_name='Zmena štatutárov')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ')),
            ],
            options={
                'verbose_name': 'Notifikačné preferencie',
                'verbose_name_plural': 'Notifikačné preferencie',
                'db_table': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_ico', models.CharField(max_length=20, verbose_name='IČO firmy')),
                ('company_name', models.CharField(max_length=255, verbose_name='Názov firmy')),
                ('event_type', models.CharField(choices=[('debt_change', 'Zmena dlhu'), ('status_change', 'Zmena statusu'), ('executive_change', 'Zmena štatutára')], max_length=30, verbose_name='Typ udalosti')),
                ('title', models.CharField(max_length=255, verbose_name='Titulok')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detaily')),
                ('sent_email', models.BooleanField(default=False, verbose_name='Email odoslaný')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ')),
            ],
            options={
                'verbose_name': 'Notifikačná udalosť',
                'verbose_name_plural': 'Notifikačné udalosti',
                'db_table': 'Notification Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='Notificatio_user_id_8b955b_idx'), models.Index(fields=['sent_email', '-created_at'], name='Notificatio_sent_em_b059ad_idx')],
            },
        ),
    ]
