# Generated by Django 6.0.1 on 2026-09-09 20:13

from django.conf import settings
from django.db import migrations, models


def backfill_delivery_status(apps, schema_editor):
    """Map the legacy boolean onto the new status lifecycle (data safety).

    Runs while both `sent_email` and `status`/`sent_at` still exist: rows that
    were flagged as emailed become `sent` (with `sent_at = created_at`);
    everything else keeps the fresh column default `pending`.
    """
    NotificationEvent = apps.get_model('notifications', 'NotificationEvent')
    NotificationEvent.objects.filter(sent_email=True).update(
        status='sent',
        sent_at=models.F('created_at'),
    )


def reverse_delivery_status(apps, schema_editor):
    """Reverse: fold the new lifecycle back onto the legacy boolean."""
    NotificationEvent = apps.get_model('notifications', 'NotificationEvent')
    NotificationEvent.objects.filter(status='sent').update(sent_email=True)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationevent',
            name='Notificatio_sent_em_b059ad_idx',
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Pokusy'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='Kedy si worker event vyhradil; staršie ako lease sa automaticky re-claimujú.', null=True, verbose_name='Rezervované workerom'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='Posledná chyba'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Odoslané'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Čaká'), ('sending', 'Odosiela sa'), ('sent', 'Odoslané'), ('failed', 'Zlyhalo')], db_index=True, default='pending', max_length=12, verbose_name='Stav odoslania'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['status', '-created_at'], name='Notificatio_status_283d7b_idx'),
        ),
        migrations.RunPython(backfill_delivery_status, reverse_delivery_status),
        migrations.RemoveField(
            model_name='notificationevent',
            name='sent_email',
        ),
    ]
