apiVersion: v1
kind: Secret
metadata:
  name: cistafirma-secrets
  namespace: cistafirma
type: Opaque
stringData:
  SECRET_KEY: change-me
  POSTGRES_DB: cistafirma
  POSTGRES_USER: cistafirma
  POSTGRES_PASSWORD: change-me
  DATABASE_URL: postgres://cistafirma:change-me@cistafirma-postgres:5432/cistafirma
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0

