# Generated by Django 6.0.1 on 2026-01-22 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(choices=[('free', 'Free'), ('plus', 'Plus'), ('pro', 'Pro'), ('business', 'Business')], unique=True)),
                ('max_watched_companies', models.IntegerField(default=10, help_text='Koľko firiem môže sledovať')),
                ('pdf_reports_per_month', models.IntegerField(default=1, help_text='Koľko reportov môže stiahnuť')),
                ('price_eur', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
