# Generated by Django 6.0.1 on 2026-02-04 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_create_default_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='Vytvorený'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='id',
            field=models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_watched_companies',
            field=models.IntegerField(db_column='Max. Firiem', default=10, help_text='Koľko firiem môže sledovať'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(db_column='Názov', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='pdf_reports_per_month',
            field=models.IntegerField(db_column='Max. PDF reportov', default=1, help_text='Koľko reportov môže stiahnuť'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_eur',
            field=models.DecimalField(db_column='Cena', decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(choices=[('free', 'Free'), ('plus', 'Plus'), ('pro', 'Pro'), ('business', 'Business')], db_column='Slug', unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='Upravený'),
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='Subscription Plans',
        ),
    ]
