apiVersion: v1
kind: Service
metadata:
  name: {{ include "cistafirma.fullname" . }}-backend
  labels:
    {{- include "cistafirma.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "cistafirma.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000

