apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cistafirma.fullname" . }}-config
  labels:
    {{- include "cistafirma.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.config.djangoSettingsModule | quote }}
  ALLOWED_HOSTS: {{ .Values.config.allowedHosts | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
  CSRF_TRUSTED_ORIGINS: {{ .Values.config.csrfTrustedOrigins | quote }}
  BACKEND_PORT: {{ .Values.config.backendPort | quote }}

