apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cistafirma.fullname" . }}-frontend
  labels:
    {{- include "cistafirma.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "cistafirma.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "cistafirma.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ include "cistafirma.frontendImage" . }}
          imagePullPolicy: {{ .Values.global.frontendImage.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 8
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

