{{- if .Values.migrateJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cistafirma.fullname" . }}-migrate
  labels:
    {{- include "cistafirma.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrateJob.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.migrateJob.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "cistafirma.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ include "cistafirma.backendImage" . }}
          imagePullPolicy: {{ .Values.global.backendImage.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: {{ include "cistafirma.fullname" . }}-config
            - secretRef:
                name: {{ include "cistafirma.existingSecret" . }}
          command:
            - sh
            - -c
            - |
              python manage.py migrate --settings=backend.settings && \
              python manage.py collectstatic --noinput --settings=backend.settings
{{- end }}

