# Generated by Django 6.0.1 on 2026-02-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync')], default='full', max_length=20, verbose_name='Typ synchronizácie')),
                ('status', models.CharField(choices=[('idle', 'Nečinný'), ('running', 'Beží'), ('paused', 'Pozastavený'), ('completed', 'Dokončený'), ('failed', 'Zlyhalo')], default='idle', max_length=20, verbose_name='Stav')),
                ('last_processed_ruz_id', models.IntegerField(blank=True, help_text='ID poslednej úspešne spracovanej firmy', null=True, verbose_name='Posledné spracované RUZ ID')),
                ('zmenene_od', models.DateField(blank=True, help_text='Dátum od ktorého sa synchronizujú zmeny', null=True, verbose_name='Zmenené od')),
                ('total_processed', models.IntegerField(default=0, verbose_name='Celkom spracovaných')),
                ('total_created', models.IntegerField(default=0, verbose_name='Nových firiem')),
                ('total_updated', models.IntegerField(default=0, verbose_name='Aktualizovaných')),
                ('total_skipped', models.IntegerField(default=0, verbose_name='Preskočených')),
                ('total_errors', models.IntegerField(default=0, verbose_name='Chýb')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Spustené')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Posledná aktivita')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dokončené')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Posledná chyba')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Poznámky')),
            ],
            options={
                'verbose_name': 'Stav synchronizácie',
                'verbose_name_plural': 'Stavy synchronizácie',
                'ordering': ['-last_activity'],
            },
        ),
    ]
