# Generated by Django 6.0.1 on 2026-02-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_add_sync_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Čaká na analýzu'), ('analyzing', 'Analyzuje sa'), ('ready', 'Pripravené na opravu'), ('repairing', 'Opravuje sa'), ('completed', 'Dokončené'), ('failed', 'Zlyhalo')], default='pending', max_length=20, verbose_name='Stav')),
                ('analyzed_min_id', models.IntegerField(blank=True, null=True, verbose_name='Minimálne analyzované ID')),
                ('analyzed_max_id', models.IntegerField(blank=True, null=True, verbose_name='Maximálne analyzované ID')),
                ('total_existing', models.IntegerField(default=0, verbose_name='Existujúcich firiem v DB')),
                ('total_missing', models.IntegerField(default=0, verbose_name='Chýbajúcich ID')),
                ('total_gaps', models.IntegerField(default=0, verbose_name='Počet dier (rozsahov)')),
                ('gap_ranges', models.JSONField(default=list, help_text='Zoznam rozsahov chýbajúcich ID: [[start, end], ...]', verbose_name='Rozsahy dier')),
                ('repair_progress_id', models.IntegerField(blank=True, help_text='Posledné opravené RUZ ID', null=True, verbose_name='Opravené do ID')),
                ('repaired_count', models.IntegerField(default=0, verbose_name='Opravených')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='Preskočených (404/deleted)')),
                ('error_count', models.IntegerField(default=0, verbose_name='Chýb')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Analyzované')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dokončené')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Posledná chyba')),
            ],
            options={
                'verbose_name': 'Analýza dier v RUZ',
                'verbose_name_plural': 'Analýzy dier v RUZ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='syncprogress',
            name='sync_type',
            field=models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('repair', 'Repair Sync')], default='full', max_length=20, verbose_name='Typ synchronizácie'),
        ),
    ]
