# Generated by Django 6.0.1 on 2026-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registers', '0008_admin_overhaul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orsrcompanyprofile',
            name='dalske_pravne_skutocnosti',
            field=models.TextField(blank=True, default='', verbose_name='Ďalšie právne skutočnosti'),
        ),
        migrations.AlterField(
            model_name='orsrcompanyprofile',
            name='konanie',
            field=models.TextField(blank=True, default='', verbose_name='Konanie menom subjektu'),
        ),
        migrations.AlterField(
            model_name='orsrcompanyprofile',
            name='kontrolna_komisia',
            field=models.JSONField(default=list, verbose_name='Kontrolná komisia'),
        ),
        migrations.AlterField(
            model_name='orsrcompanyprofile',
            name='oddiel_type',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Typ ORSR (Sr/Dr/...)'),
        ),
        migrations.AlterField(
            model_name='orsrcompanyprofile',
            name='predstavenstvo',
            field=models.JSONField(default=list, verbose_name='Predstavenstvo'),
        ),
        migrations.AlterField(
            model_name='orsrcompanyprofile',
            name='zakladny_clensky_vklad',
            field=models.TextField(blank=True, default='', verbose_name='Základný členský vklad'),
        ),
        migrations.AlterField(
            model_name='orsrcompanyprofile',
            name='zapisovane_zakladne_imanie',
            field=models.TextField(blank=True, default='', verbose_name='Zapisované základné imanie'),
        ),
    ]
