# Generated by Django 6.0.1 on 2026-08-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0010_add_individual_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='job_type',
            field=models.CharField(choices=[('ruz_full', 'RUZ Full Sync'), ('ruz_full_firmy', 'RUZ Full Sync - Firmy only'), ('ruz_full_szco', 'RUZ Full Sync - SZCO only'), ('ruz_incremental', 'RUZ Incremental'), ('ruz_repair', 'RUZ Repair (gap fill)'), ('orsr_batch', 'ORSR Batch'), ('financials_batch', 'Financials Batch'), ('insurance_batch', 'Insurance Debt Batch'), ('fs_update', 'Finančná správa'), ('manual', 'Manuálne (jedna firma)')], max_length=30, verbose_name='Typ úlohy'),
        ),
    ]
