# Generated by Django 6.0.1 on 2026-09-08

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("registers", "0011_alter_syncjob_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjob",
            name="concurrency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="Kľúč súbežnosti",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncjob",
            constraint=models.UniqueConstraint(
                condition=Q(
                    concurrency_key="ruz:global",
                    status__in=["queued", "running"],
                ),
                fields=("concurrency_key",),
                name="reg_one_active_ruz_job",
            ),
        ),
    ]
