# Generated by Django 6.0.1 on 2026-09-11 18:00
#
# Drops `SyncJobItem`, the per-item record inside a `SyncJob`. It held **zero
# rows** in the live database when this was written: its only writer was
# `sync_engine.record_item`, called only by the `tracked_sync_task` decorator,
# which was applied to no task. The two readers went with it -- the
# `sync/jobs/{pk}/items/` endpoint (never called by the frontend) and
# `retry-failed`, which always retried an empty list. So this migration
# deletes nothing that exists; it removes a table that could only ever be
# empty, and with it the appearance of a per-company trace that was never
# written. Per-company attempts are recorded in `CompanySyncStatus`, one row
# per company per source, which is untouched.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0012_syncjob_ruz_singleton'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='syncjobitem',
            name='reg_sji_job_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='syncjobitem',
            name='reg_sji_status_comp_idx',
        ),
        migrations.DeleteModel(
            name='SyncJobItem',
        ),
    ]
