# Generated by Django 6.0.1 on 2026-09-12
#
# Adds `CompanySyncStatus.last_detail`, the durable home for a sync result's own
# sentence. `last_error` already stores it -- but only on failure, because
# `update_company_status` writes `error="" if success`. The companies this
# column exists for are the ones that *succeeded*: the registry answered, the
# statements were there, and none of them produced a row. Their attempt is
# `answered`, so `error` is blanked, `last_error` stays empty, and the sentence
# naming which of the four causes produced it survives only in the Celery log.
# `ANSWERED_RETRY_AFTER` then pushes the next attempt out a year, so no later
# run recovers it either.
#
# Writer: `update_company_status(detail=...)`, keyword-only and `None`-defaulted
# so the four sources with nothing to say about themselves (ORSR, VZP,
# Sociálna poisťovňa, RUZ dates) leave the column at whatever the last caller
# that did pass one wrote -- `None` means "nothing to say", which is not the
# same as "the reason is empty".
#
# `blank=True, default=""` makes this a metadata-only add on Postgres: no table
# rewrite, and existing rows take the default.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0013_delete_syncjobitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysyncstatus',
            name='last_detail',
            field=models.TextField(
                blank=True,
                default='',
                verbose_name='Detail posledného pokusu',
            ),
        ),
    ]
