# Generated by Django 6.0.1 on 2026-09-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0014_companysyncstatus_last_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysyncstatus',
            name='parser_revision',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Revízia parsera'),
        ),
    ]
