# Generated by Django 6.0.1 on 2026-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0015_companysyncstatus_parser_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualentity',
            name='ico',
            field=models.CharField(db_column='ICO', help_text='IČO fyzickej osoby', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='orsrcompanyprofile',
            name='ico',
            field=models.CharField(db_index=True, max_length=20, verbose_name='IČO'),
        ),
    ]
