# Generated by Django 6.0.1 on 2026-09-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0016_alter_individualentity_ico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysyncstatus',
            name='last_error_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('http_429', 'HTTP 429 (rate limit)'), ('http_404', 'HTTP 404 (not found)'), ('http_5xx', 'HTTP 5xx (server error)'), ('timeout', 'Timeout'), ('parse_error', 'Parsing chyba'), ('network', 'Sieťová chyba'), ('not_in_register', 'Register neeviduje'), ('validation', 'Validačná chyba'), ('unknown', 'Neznáma')], default='', max_length=20, verbose_name='Typ chyby'),
        ),
    ]
