# Generated by Django 6.0.1 on 2026-02-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruz_id', models.IntegerField(db_column='RUZ ID', help_text='Identifikátor účtovnej jednotky z RUZ API', unique=True)),
                ('ico', models.CharField(db_column='ICO', help_text='IČO účtovnej jednotky', max_length=8, unique=True)),
                ('dic', models.CharField(blank=True, db_column='DIC', help_text='DIČ účtovnej jednotky', max_length=10, null=True)),
                ('sid', models.CharField(blank=True, db_column='SID', help_text='SID účtovnej jednotky', max_length=5, null=True)),
                ('nazov_UJ', models.CharField(db_column='Názov UJ', help_text='Názov účtovnej jednotky', max_length=500)),
                ('mesto', models.CharField(blank=True, db_column='Mesto', help_text='Adresa účtovnej jednotky, mesto', max_length=200, null=True)),
                ('ulica', models.CharField(blank=True, db_column='Ulica', help_text='Adresa účtovnej jednotky, ulica s číslom', max_length=200, null=True)),
                ('psc', models.CharField(blank=True, db_column='PSČ', help_text='Adresa účtovnej jednotky, PSČ', max_length=10, null=True)),
                ('datum_zalozenia', models.DateField(blank=True, db_column='Dátum založenia UJ', help_text='Dátum založenia účtovnej jednotky', null=True)),
                ('datum_zrusenia', models.DateField(blank=True, db_column='Dátum zrušenia UJ', help_text='Dátum zrušenia účtovnej jednotky', null=True)),
                ('pravna_forma', models.CharField(blank=True, db_column='Právna forma', help_text='Kód právnej formy', max_length=100, null=True)),
                ('sk_NACE', models.CharField(blank=True, db_column='NACE', help_text='Kód SK NACE klasifikácie', max_length=100, null=True)),
                ('velkost_organizacie', models.CharField(blank=True, db_column='Veľkosť', help_text='Kód kategórie veľkosti organizácie', max_length=100, null=True)),
                ('druh_vlastnictva', models.CharField(blank=True, db_column='Vlastníctvo', help_text='Kód druhu vlastníctva', max_length=100, null=True)),
                ('kraj', models.CharField(blank=True, db_column='Kraj', help_text='Sídlo účtovnej jednotky, kód kraja', max_length=100, null=True)),
                ('okres', models.CharField(blank=True, db_column='Okres', help_text='Sídlo účtovnej jednotky, kód okresu', max_length=100, null=True)),
                ('sidlo', models.CharField(blank=True, db_column='Sídlo', help_text='Sídlo účtovnej jednotky, kód obce alebo mesta', max_length=100, null=True)),
                ('konsolidovana', models.BooleanField(db_column='Konsolidovaná', default=False, help_text='Príznak, či jednotka obsahuje aspoň jednu konsolidovanú účtovnú závierku')),
                ('id_uctovnych_zavierok', models.JSONField(db_column='ID UZ', default=list, help_text='Zoznam identifikátorov všetkých súvisiacich účtovných závierok')),
                ('id_vyrocnych_sprav', models.JSONField(db_column='ID VS', default=list, help_text='Zoznam identifikátorov všetkých súvisiacich výročných správ')),
                ('zdroj_dat', models.CharField(blank=True, db_column='Kód zdroja', help_text='Kód zdroja, z ktorého pochádzajú dáta', max_length=30, null=True)),
                ('datum_poslednej_upravy', models.DateField(blank=True, db_column='Dátum a čas kontroly RUZ', help_text='Dátum poslednej úpravy', null=True)),
                ('debt_vszp', models.DecimalField(blank=True, db_column='Dlh vo VSZP', decimal_places=2, help_text='Dlh vo Všeobecnej zdravotnej poisťovni', max_digits=10, null=True, verbose_name='Dlh vo VSZP')),
                ('debt_soc_poist', models.DecimalField(blank=True, db_column='Dlh v SP', decimal_places=2, help_text='Dlh v Sociálnej poisťovni', max_digits=10, null=True, verbose_name='Dlh v SP')),
                ('last_insurance_debt', models.DateTimeField(blank=True, db_column='Dátum a čas kontroly VSZP/SP', help_text='Dátum a čas poslednej kontroly dlhov v poisťovniach', null=True, verbose_name='Posledná kontrola dlhov vo VSZP a SP')),
                ('tax_debt', models.DecimalField(blank=True, db_column='Daňový dlh', decimal_places=2, help_text='Dlh na daniach z FS', max_digits=10, null=True, verbose_name='Daňový dlh')),
                ('vat_payer', models.BooleanField(blank=True, db_column='Platiteľ DPH', help_text='Je platiteľ DPH? z FS', null=True, verbose_name='Platiteľ DPH')),
                ('ic_dph', models.CharField(blank=True, db_column='IČ DPH', help_text='Identifikačné číslo pre daň z pridanej hodnoty', max_length=20, null=True, verbose_name='IČ DPH')),
                ('datum_reg_dph', models.DateField(blank=True, db_column='Dátum registrácie DPH', help_text='Dátum registrácie subjektu pre DPH', null=True, verbose_name='Dátum registrácie DPH')),
                ('bank_accounts', models.JSONField(blank=True, db_column='IBANs', default=list, help_text='Zoznam bankových účtov subjektu pre DPH', verbose_name='Bankové účty')),
                ('vat_deleted_date', models.DateField(blank=True, db_column='Dátum výmazu DPH', help_text='Dátum výmazu zo zoznamu platiteľov DPH', null=True, verbose_name='Dátum výmazu z DPH')),
                ('vat_deleted_reason', models.CharField(blank=True, db_column='Dôvod výmazu DPH', help_text='Dôvod výmazu zo zoznamu platiteľov DPH', max_length=100, null=True, verbose_name='Dôvod výmazu z DPH')),
                ('tax_reliability', models.CharField(blank=True, db_column='Index daňovej spoľahlivosti', help_text='Index daňovej spoľahlivosti z FS (spoľahlivý, vysoko spoľahlivý, nespoľahlivý)', max_length=50, null=True, verbose_name='Index daňovej spoľahlivosti')),
                ('fs_update_date', models.DateTimeField(blank=True, db_column='Dátum kontroly FS', help_text='Dátum poslednej aktualizácie dát z FS', null=True, verbose_name='Posledná aktualizácia z FS')),
            ],
            options={
                'db_table': 'Companies and SZCO',
            },
        ),
    ]
