# Generated by Django 6.0.1 on 2026-01-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruz_id', models.IntegerField(help_text='Identifikátor účtovnej jednotky z RUZ API', unique=True)),
                ('ico', models.CharField(help_text='IČO účtovnej jednotky', max_length=8, unique=True)),
                ('dic', models.CharField(blank=True, help_text='DIČ účtovnej jednotky', max_length=10, null=True)),
                ('sid', models.CharField(blank=True, help_text='SID účtovnej jednotky', max_length=5, null=True)),
                ('nazovUJ', models.CharField(help_text='Názov účtovnej jednotky', max_length=500)),
                ('mesto', models.CharField(blank=True, help_text='Adresa účtovnej jednotky, mesto', max_length=200, null=True)),
                ('ulica', models.CharField(blank=True, help_text='Adresa účtovnej jednotky, ulica s číslom', max_length=200, null=True)),
                ('psc', models.CharField(blank=True, help_text='Adresa účtovnej jednotky, PSČ', max_length=10, null=True)),
                ('datumZalozenia', models.DateField(blank=True, help_text='Dátum založenia účtovnej jednotky', null=True)),
                ('datumZrusenia', models.DateField(blank=True, help_text='Dátum zrušenia účtovnej jednotky', null=True)),
                ('pravnaForma', models.CharField(blank=True, help_text='Kód právnej formy', max_length=100, null=True)),
                ('skNace', models.CharField(blank=True, help_text='Kód SK NACE klasifikácie', max_length=100, null=True)),
                ('velkostOrganizacie', models.CharField(blank=True, help_text='Kód kategórie veľkosti organizácie', max_length=100, null=True)),
                ('druhVlastnictva', models.CharField(blank=True, help_text='Kód druhu vlastníctva', max_length=100, null=True)),
                ('kraj', models.CharField(blank=True, help_text='Sídlo účtovnej jednotky, kód kraja', max_length=100, null=True)),
                ('okres', models.CharField(blank=True, help_text='Sídlo účtovnej jednotky, kód okresu', max_length=100, null=True)),
                ('sidlo', models.CharField(blank=True, help_text='Sídlo účtovnej jednotky, kód obce alebo mesta', max_length=100, null=True)),
                ('konsolidovana', models.BooleanField(default=False, help_text='Príznak, či jednotka obsahuje aspoň jednu konsolidovanú účtovnú závierku')),
                ('idUctovnychZavierok', models.JSONField(default=list, help_text='Zoznam identifikátorov všetkých súvisiacich účtovných závierok')),
                ('idVyrocnychSprav', models.JSONField(default=list, help_text='Zoznam identifikátorov všetkých súvisiacich výročných správ')),
                ('zdrojDat', models.CharField(blank=True, help_text='Kód zdroja, z ktorého pochádzajú dáta', max_length=30, null=True)),
                ('datumPoslednejUpravy', models.DateField(help_text='Dátum poslednej úpravy')),
            ],
        ),
    ]
