# Generated by Django 6.0.1 on 2026-01-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='debt_soc_poist',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dlh v Sociálnej poisťovni', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='debt_vszp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dlh vo Všeobecnej zdravotnej poisťovni', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_insurance_debt',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas poslednej kontroly dlhov v poisťovniach', null=True),
        ),
    ]
