# Generated by Django 6.0.1 on 2026-02-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-datum_poslednej_upravy', 'nazov_UJ'], 'verbose_name': 'Firma', 'verbose_name_plural': 'Firmy'},
        ),
    ]
