# Generated by Django 6.0.1 on 2026-01-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_debt_soc_poist_company_debt_vszp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fs_update_date',
            field=models.DateTimeField(blank=True, help_text='Dátum poslednej aktualizácie dát z Finančnej správy', null=True, verbose_name='Posledná aktualizácia z FS'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_debt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dlh na daniach z Finančnej správy', max_digits=10, null=True, verbose_name='Daňový dlh'),
        ),
        migrations.AlterField(
            model_name='company',
            name='debt_soc_poist',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dlh v Sociálnej poisťovni', max_digits=10, null=True, verbose_name='Dlh v SP'),
        ),
        migrations.AlterField(
            model_name='company',
            name='debt_vszp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dlh vo Všeobecnej zdravotnej poisťovni', max_digits=10, null=True, verbose_name='Dlh vo VSZP'),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_insurance_debt',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas poslednej kontroly dlhov v poisťovniach', null=True, verbose_name='Posledná kontrola dlhov vo VSZP a SP'),
        ),
    ]
