# Generated by Django 6.0.1 on 2026-01-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_fs_update_date_company_tax_debt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='datumPoslednejUpravy',
        ),
        migrations.RemoveField(
            model_name='company',
            name='datumZalozenia',
        ),
        migrations.RemoveField(
            model_name='company',
            name='datumZrusenia',
        ),
        migrations.RemoveField(
            model_name='company',
            name='druhVlastnictva',
        ),
        migrations.RemoveField(
            model_name='company',
            name='idUctovnychZavierok',
        ),
        migrations.RemoveField(
            model_name='company',
            name='idVyrocnychSprav',
        ),
        migrations.RemoveField(
            model_name='company',
            name='nazovUJ',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pravnaForma',
        ),
        migrations.RemoveField(
            model_name='company',
            name='skNace',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tax_debt',
        ),
        migrations.RemoveField(
            model_name='company',
            name='velkostOrganizacie',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zdrojDat',
        ),
        migrations.AddField(
            model_name='company',
            name='datum_poslednej_upravy',
            field=models.DateField(blank=True, db_column='Dátum a čas kontroly RUZ', help_text='Dátum poslednej úpravy', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='datum_zalozenia',
            field=models.DateField(blank=True, db_column='Dátum založenia UJ', help_text='Dátum založenia účtovnej jednotky', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='datum_zrusenia',
            field=models.DateField(blank=True, db_column='Dátum zrušenia UJ', help_text='Dátum zrušenia účtovnej jednotky', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='druh_vlastnictva',
            field=models.CharField(blank=True, db_column='Vlastníctvo', help_text='Kód druhu vlastníctva', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='id_uctovnych_zavierok',
            field=models.JSONField(db_column='ID UZ', default=list, help_text='Zoznam identifikátorov všetkých súvisiacich účtovných závierok'),
        ),
        migrations.AddField(
            model_name='company',
            name='id_vyrocnych_sprav',
            field=models.JSONField(db_column='ID VS', default=list, help_text='Zoznam identifikátorov všetkých súvisiacich výročných správ'),
        ),
        migrations.AddField(
            model_name='company',
            name='nazov_UJ',
            field=models.CharField(db_column='Názov UJ', default='Neznáma firma', help_text='Názov účtovnej jednotky', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='pravna_forma',
            field=models.CharField(blank=True, db_column='Právna forma', help_text='Kód právnej formy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sk_NACE',
            field=models.CharField(blank=True, db_column='NACE', help_text='Kód SK NACE klasifikácie', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_debt',
            field=models.DecimalField(blank=True, db_column='Dlh DPH', decimal_places=2, help_text='Dlh na daniach z FS', max_digits=10, null=True, verbose_name='Daňový dlh'),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_payer',
            field=models.BooleanField(blank=True, db_column='Platiteľ DPH', help_text='Je platiteľ DPH? z FS', null=True, verbose_name='Platiteľ DPH'),
        ),
        migrations.AddField(
            model_name='company',
            name='velkost_organizacie',
            field=models.CharField(blank=True, db_column='Veľkosť', help_text='Kód kategórie veľkosti organizácie', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zdroj_dat',
            field=models.CharField(blank=True, db_column='Kód zdroja', help_text='Kód zdroja, z ktorého pochádzajú dáta', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='debt_soc_poist',
            field=models.DecimalField(blank=True, db_column='Dlh v SP', decimal_places=2, help_text='Dlh v Sociálnej poisťovni', max_digits=10, null=True, verbose_name='Dlh v SP'),
        ),
        migrations.AlterField(
            model_name='company',
            name='debt_vszp',
            field=models.DecimalField(blank=True, db_column='Dlh vo VSZP', decimal_places=2, help_text='Dlh vo Všeobecnej zdravotnej poisťovni', max_digits=10, null=True, verbose_name='Dlh vo VSZP'),
        ),
        migrations.AlterField(
            model_name='company',
            name='dic',
            field=models.CharField(blank=True, db_column='DIC', help_text='DIČ účtovnej jednotky', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fs_update_date',
            field=models.DateTimeField(blank=True, db_column='Dátum kontroly FS', help_text='Dátum poslednej aktualizácie dát z FS', null=True, verbose_name='Posledná aktualizácia z FS'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ico',
            field=models.CharField(db_column='ICO', help_text='IČO účtovnej jednotky', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='konsolidovana',
            field=models.BooleanField(db_column='Konsolidovaná', default=False, help_text='Príznak, či jednotka obsahuje aspoň jednu konsolidovanú účtovnú závierku'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kraj',
            field=models.CharField(blank=True, db_column='Kraj', help_text='Sídlo účtovnej jednotky, kód kraja', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_insurance_debt',
            field=models.DateTimeField(blank=True, db_column='Dátum a čas kontroly VSZP/SP', help_text='Dátum a čas poslednej kontroly dlhov v poisťovniach', null=True, verbose_name='Posledná kontrola dlhov vo VSZP a SP'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mesto',
            field=models.CharField(blank=True, db_column='Mesto', help_text='Adresa účtovnej jednotky, mesto', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='okres',
            field=models.CharField(blank=True, db_column='Okres', help_text='Sídlo účtovnej jednotky, kód okresu', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='psc',
            field=models.CharField(blank=True, db_column='PSČ', help_text='Adresa účtovnej jednotky, PSČ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ruz_id',
            field=models.IntegerField(db_column='RUZ ID', help_text='Identifikátor účtovnej jednotky z RUZ API', unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sid',
            field=models.CharField(blank=True, db_column='SID', help_text='SID účtovnej jednotky', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sidlo',
            field=models.CharField(blank=True, db_column='Sídlo', help_text='Sídlo účtovnej jednotky, kód obce alebo mesta', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ulica',
            field=models.CharField(blank=True, db_column='Ulica', help_text='Adresa účtovnej jednotky, ulica s číslom', max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table='Firmy',
        ),
    ]
