# Generated by Django 6.0.1 on 2026-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_datumposlednejupravy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='vat_debt',
        ),
        migrations.AddField(
            model_name='company',
            name='datum_reg_dph',
            field=models.DateField(blank=True, db_column='Dátum registrácie DPH', help_text='Dátum registrácie subjektu pre DPH', null=True, verbose_name='Dátum registrácie DPH'),
        ),
        migrations.AddField(
            model_name='company',
            name='ic_dph',
            field=models.CharField(blank=True, db_column='IČ DPH', help_text='Identifikačné číslo pre daň z pridanej hodnoty', max_length=20, null=True, verbose_name='IČ DPH'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_debt',
            field=models.DecimalField(blank=True, db_column='Daňový dlh', decimal_places=2, help_text='Dlh na daniach z FS', max_digits=10, null=True, verbose_name='Daňový dlh'),
        ),
    ]
