# Generated by Django 6.0.1 on 2026-05-31 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_sector_benchmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico', models.CharField(max_length=20, verbose_name='IČO')),
                ('name', models.CharField(max_length=255, verbose_name='Názov firmy')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Vyhľadané')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'História vyhľadávania',
                'verbose_name_plural': 'História vyhľadávania',
                'db_table': 'Search History',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['user', '-searched_at'], name='Search Hist_user_id_a37a26_idx')],
            },
        ),
    ]
