# Generated by Django 6.0.1 on 2026-06-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('companies', '0007_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='uses_ifrs',
            field=models.BooleanField(db_column='Používa IFRS', default=False,
                                      help_text='Firma účtuje podľa IFRS — finančné výkazy sú v RUZ len ako PDF'),
        ),
    ]
