# Generated by Django 5.2.8 on 2026-07-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_add_uses_ifrs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['mesto'], name='company_mesto_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['psc'], name='company_psc_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['kraj'], name='company_kraj_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['pravna_forma'], name='company_pravna_forma_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['velkost_organizacie'], name='company_velkost_org_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['datum_zalozenia'], name='company_datum_zaloz_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['debt_vszp'], name='company_debt_vszp_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['debt_soc_poist'], name='company_debt_sp_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['tax_debt'], name='company_tax_debt_idx'),
        ),
    ]
