# Generated by Django 5.2.8 on 2026-07-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_add_company_filter_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['kraj', 'datum_zrusenia'], name='company_kraj_active_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['pravna_forma', 'datum_zrusenia'], name='company_form_active_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['mesto', 'datum_zrusenia'], name='company_mesto_active_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['velkost_organizacie', 'datum_zrusenia'], name='company_size_active_idx'),
        ),
    ]
