# Generated by Django 5.2.8 on 2026-08-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_add_company_composite_filter_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['sk_NACE'], name='company_nace_idx'),
        ),
    ]
