# Generated by Django 5.2.8 on 2026-08-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_add_nace_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['sk_NACE', 'datum_zrusenia'], name='company_nace_active_idx'),
        ),
    ]
