# Generated by Django 6.0.1 on 2026-08-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_add_pattern_ops_structured_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='companyfinancialresult',
            index=models.Index(fields=['company'], name='cfr_company_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfinancialresult',
            index=models.Index(fields=['company', '-year'], name='cfr_company_year_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfinancialresult',
            index=models.Index(fields=['year'], name='cfr_year_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfinancialresult',
            index=models.Index(fields=['company', 'year'], name='cfr_company_year_unique_idx'),
        ),
    ]
