# Generated by Django 6.0.1 on 2026-09-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_companyfinancialresult_cfr_company_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfinancialresult',
            name='profit_after_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Zisk po zdanení'),
        ),
        migrations.AlterField(
            model_name='companyfinancialresult',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Výsledok hospodárenia z hospodárskej činnosti'),
        ),
    ]
