# Generated by Django 6.0.1 on 2026-09-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_companyfinancialresult_profit_after_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfinancialresult',
            name='assets_current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Obežný majetok celkom'),
        ),
        migrations.AddField(
            model_name='companyfinancialresult',
            name='assets_financial_short',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Krátkodobý finančný majetok'),
        ),
    ]
