# Generated by Django 6.0.1 on 2026-09-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_companyfinancialresult_assets_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfinancialresult',
            name='parser_revision',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='Revízia parsera'),
        ),
    ]
