# Generated by Django 6.0.1 on 2026-09-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_companyfinancialresult_parser_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfinancialresult',
            name='ruz_statement_id',
            field=models.BigIntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='ID účtovnej závierky v RUZ'),
        ),
    ]
