# Generated by Django 6.0.1 on 2026-09-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_companyfinancialresult_ruz_statement_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCodeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psc', models.CharField(help_text='Normalizovaná podoba bez medzier — kľúč spojenia s Company.psc', max_length=5, unique=True, verbose_name='PSČ')),
                ('lat', models.FloatField(verbose_name='Zemepisná šírka')),
                ('lon', models.FloatField(verbose_name='Zemepisná dĺžka')),
                ('radius_m', models.PositiveIntegerField(help_text='Pokryje 90 % adresných bodov tejto PSČ. Medián 1 980 m', verbose_name='Polomer (m)')),
                ('point_count', models.PositiveIntegerField(help_text='Z koľkých bodov je počítaný; pod 20 sa oblasť neukladá', verbose_name='Počet adresných bodov')),
                ('dominant_obec', models.CharField(blank=True, max_length=200, verbose_name='Prevažujúca obec')),
                ('obec_count', models.PositiveSmallIntegerField(default=1, help_text='Koľko obcí táto PSČ pokrýva; 1 = sedí s obcou', verbose_name='Počet obcí v PSČ')),
                ('okres', models.CharField(blank=True, max_length=200, verbose_name='Okres')),
                ('kraj', models.CharField(blank=True, max_length=100, verbose_name='Kraj')),
                ('source_version', models.CharField(blank=True, help_text='dct:modified datasetu, z ktorého dáta sú (formát YYYY-MM-DD)', max_length=40, verbose_name='Verzia zdroja')),
                ('imported_at', models.DateTimeField(auto_now=True, verbose_name='Importované')),
            ],
            options={
                'verbose_name': 'PSČ oblasť',
                'verbose_name_plural': 'PSČ oblasti',
                'ordering': ['psc'],
                'indexes': [models.Index(fields=['okres'], name='pscarea_okres_idx')],
            },
        ),
    ]
