# Generated by Django 6.0.1 on 2026-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_postalcodearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ico',
            field=models.CharField(db_column='ICO', help_text='IČO účtovnej jednotky', max_length=20, unique=True),
        ),
    ]
