# Generated by Django 6.0.1 on 2026-09-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_alter_company_ico'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='seat_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Sídlo — zemepisná šírka'),
        ),
        migrations.AddField(
            model_name='company',
            name='seat_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Sídlo — zemepisná dĺžka'),
        ),
        migrations.AddField(
            model_name='company',
            name='seat_matched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sídlo spárované'),
        ),
        migrations.AddField(
            model_name='company',
            name='seat_point_count',
            field=models.PositiveIntegerField(blank=True, help_text='Z koľkých bodov registra je sídlo počítané', null=True, verbose_name='Počet adresných bodov'),
        ),
        migrations.AddField(
            model_name='company',
            name='seat_precision',
            field=models.CharField(blank=True, choices=[('building', 'Budova'), ('street', 'Ulica'), ('postal_code', 'PSČ')], help_text='building = budova, street = stred ulice, postal_code = len PSČ', max_length=20, verbose_name='Presnosť sídla'),
        ),
        migrations.AddField(
            model_name='company',
            name='seat_radius_m',
            field=models.PositiveIntegerField(blank=True, help_text='0 pri budove; pri ulici polomer, ktorý pokryje 90 % jej bodov', null=True, verbose_name='Polomer sídla (m)'),
        ),
        migrations.AddField(
            model_name='company',
            name='seat_tier',
            field=models.CharField(blank=True, help_text='Ktorá vrstva odpovedala (psc_ulica_orient, …) — dôkaz, nie popis', max_length=40, verbose_name='Vrstva párovania'),
        ),
        migrations.CreateModel(
            name='AddressPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psc', models.CharField(max_length=5, verbose_name='PSČ')),
                ('obec', models.CharField(help_text='Normalizovaná podoba — kľúč spojenia s Company.mesto', max_length=200, verbose_name='Obec')),
                ('ulica', models.CharField(blank=True, help_text='Normalizovaný kľúč; prázdne = vidiecky riadok, adresu nesie číslo', max_length=200, verbose_name='Ulica')),
                ('supisne_cislo', models.CharField(blank=True, max_length=20, verbose_name='Súpisné číslo')),
                ('orientacne_cislo', models.CharField(blank=True, max_length=20, verbose_name='Orientačné číslo')),
                ('lat', models.FloatField(verbose_name='Zemepisná šírka')),
                ('lon', models.FloatField(verbose_name='Zemepisná dĺžka')),
                ('source_version', models.CharField(blank=True, help_text='dct:modified datasetu, z ktorého dáta sú (formát YYYY-MM-DD)', max_length=40, verbose_name='Verzia zdroja')),
            ],
            options={
                'verbose_name': 'Adresný bod',
                'verbose_name_plural': 'Adresné body',
                'indexes': [models.Index(fields=['psc', 'ulica', 'orientacne_cislo'], name='addr_psc_ul_orient_idx'), models.Index(fields=['psc', 'ulica', 'supisne_cislo'], name='addr_psc_ul_supis_idx'), models.Index(fields=['obec', 'ulica', 'orientacne_cislo'], name='addr_obec_ul_orient_idx'), models.Index(fields=['obec', 'ulica', 'supisne_cislo'], name='addr_obec_ul_supis_idx')],
            },
        ),
    ]
