# Generated by Django 6.0.1 on 2026-09-15 18:55
#
# One nullable column, no default and no backfill, so this is a catalogue-only
# change on PostgreSQL 11+: `ALTER TABLE ... ADD COLUMN ... NULL` takes an
# ACCESS EXCLUSIVE lock for the length of the catalogue write and does not
# rewrite the 449 776-row table. The reverse is a DROP COLUMN, which loses only
# this flag -- `debt_soc_poist` and the sync-status rows are untouched by both
# directions.
#
# NULL for every existing row is the intended state, not a gap to be filled in
# a data migration: it means "we have not read this company since the column
# existed", which is true. The insurance rotation sets it as it works through
# the table, 14 400 companies per 12-hour tick.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_company_seat_lat_company_seat_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='social_listed_without_amount',
            field=models.BooleanField(blank=True, db_column='SP bez zverejnenej sumy', help_text='Sociálna poisťovňa uvádza spoločnosť v zozname dlžníkov bez zverejnenej sumy (nesplnená vykazovacia povinnosť)', null=True, verbose_name='Evidencia v SP bez sumy'),
        ),
    ]
