# Generated by Django 6.0.1 on 2026-05-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_companyfinancialresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Fingerprint')),
                ('name', models.CharField(max_length=500, verbose_name='Meno')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Titul')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresa')),
                ('person_ico', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='IČO osoby')),
                ('is_legal_entity', models.BooleanField(default=False, verbose_name='Právnická osoba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_person', to='companies.company', verbose_name='Prepojená firma')),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
            },
        ),
        migrations.CreateModel(
            name='PersonCompanyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('konatel', 'Konateľ'), ('spolocnik', 'Spoločník'), ('prokurista', 'Prokurista'), ('clen_predstavenstva', 'Člen predstavenstva'), ('predseda_predstavenstva', 'Predseda predstavenstva'), ('clen_dozornej_rady', 'Člen dozornej rady'), ('clen_kontrolnej_komisie', 'Člen kontrolnej komisie'), ('akcionar', 'Akcionár'), ('riaditel', 'Riaditeľ'), ('ine', 'Iné')], default='ine', max_length=50, verbose_name='Rola')),
                ('role_display', models.CharField(blank=True, default='', max_length=200, verbose_name='Pôvodný text roly')),
                ('vznik_funkcie', models.DateField(blank=True, null=True, verbose_name='Vznik funkcie')),
                ('zanik_funkcie', models.DateField(blank=True, null=True, verbose_name='Zánik funkcie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktívna')),
                ('source', models.CharField(default='orsr', max_length=20, verbose_name='Zdroj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relations', to='companies.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_relations', to='connections.person')),
            ],
            options={
                'verbose_name': 'Prepojenie osoba–firma',
                'verbose_name_plural': 'Prepojenia osoba–firma',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='connections_name_33edfe_idx'),
        ),
        migrations.AddIndex(
            model_name='personcompanyrelation',
            index=models.Index(fields=['company', 'is_active'], name='connections_company_7fec84_idx'),
        ),
        migrations.AddIndex(
            model_name='personcompanyrelation',
            index=models.Index(fields=['person', 'is_active'], name='connections_person__8f1a15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personcompanyrelation',
            unique_together={('person', 'company', 'role', 'vznik_funkcie')},
        ),
    ]
