# Generated by Django 6.0.1 on 2026-09-13 10:07

from django.db import migrations, models


def every_relation_was_a_claim(apps, schema_editor):
    """Move every existing relation to "we do not know".

    Until now `PersonExtractionService` wrote `is_active=True` on every row it
    created and never wrote `zanik_funkcie` at all, so all 64 128 relations
    asserted a currency nothing had checked. The evidence that it could not be
    trusted: six people still marked active in `Poľnohospodárske družstvo
    Trávnik` (00363243), a dissolved company, whose RPO record reports a
    `validTo` for each of them.

    None of these rows can be rescued in place -- the history they would need
    was read from the source and thrown away one step before the database.
    They become null, which reads as "not recorded" rather than "no", and the
    next sync of each company replaces it with a real answer. That is the point
    of the change: an unverified yes is the one answer we must not keep.
    """
    PersonCompanyRelation = apps.get_model("connections", "PersonCompanyRelation")
    PersonCompanyRelation.objects.filter(is_active=True).update(is_active=None)


def no_way_back(apps, schema_editor):
    """Irreversible on purpose.

    Reversing would have to re-assert the `True` this migration exists to
    withdraw, and the information needed to do better is not in the table.
    """
    raise migrations.exceptions.IrreversibleError(
        "The previous values were unverified claims; they cannot be restored."
    )


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personcompanyrelation",
            name="is_active",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text=(
                    "True/False = the source states it; null = the function's "
                    "history was never read for this company, so we do not know."
                ),
                null=True,
                verbose_name="Aktívna",
            ),
        ),
        migrations.RunPython(every_relation_was_a_claim, no_way_back),
    ]
