# Generated by Django 6.0.1 on 2026-09-13 10:08

from django.db import migrations, models


def fill_the_searchable_name(apps, schema_editor):
    """Backfill `name_normalized` for the 44 897 persons already stored.

    The column is added blank and would otherwise stay blank for every existing
    row -- and a blank `name_normalized` is not an error anywhere: those people
    would simply never be found by name, on a page that looks like it works.
    So the backfill runs in the same migration as the column, not after it.

    The normalisation is duplicated here in full rather than imported from
    `connections.models`, because a migration must keep producing the same
    result after the function it would import has been changed.
    """
    import re
    import unicodedata

    Person = apps.get_model("connections", "Person")

    def normalize(name: str, title: str) -> str:
        decomposed = unicodedata.normalize("NFKD", f"{title} {name}".lower())
        without_marks = "".join(c for c in decomposed if not unicodedata.combining(c))
        return re.sub(r"\s+", " ", without_marks).strip()

    batch = []
    for person in Person.objects.all().only("id", "name", "title").iterator(chunk_size=2000):
        batch.append(Person(id=person.id, name_normalized=normalize(person.name, person.title)))
        if len(batch) >= 2000:
            Person.objects.bulk_update(batch, ["name_normalized"])
            batch = []
    if batch:
        Person.objects.bulk_update(batch, ["name_normalized"])


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0002_is_active_is_three_valued"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="name_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="`title` + `name`, diacritics stripped, for searching.",
                max_length=700,
                verbose_name="Meno bez diakritiky",
            ),
        ),
        migrations.RunPython(fill_the_searchable_name, migrations.RunPython.noop),
    ]
