# Generated by Django 6.0.1 on 2026-09-15 18:11

from django.db import migrations, models

#: The stem every spelling of the register's line shares: `Dátum narodenia:`,
#: `Dátum narodenia`, and any variant that writes "Dátum" without its accents
#: still contains "naroden", which carries none. Matched case-insensitively, so
#: this is the widest filter that cannot also catch an ordinary address.
_BIRTH_STEM = "naroden"


def move_the_birth_date_out_of_the_address(apps, schema_editor):
    """The register's birth-date line stops being stored as an address.

    The ORSR reader appended every unrecognised line of a person's block to the
    address, and `Dátum narodenia: 20.08.1992` is one of them. That was not
    merely a wrong label. `compute_fingerprint` reads an address by its last
    non-numeric component, so the line *became the row's identity*:

        name:matej vacha|addr:datum narodenia: 20.08.1992

    Measured 2026-09-15: **14** `Person` rows of 121 257 carry the line, and in
    all 14 it is the *whole* address -- the register stated no address for that
    entry at all. So each one holds a fingerprint that no future read can
    produce, because the reader no longer puts the line into the address.

    That is what makes leaving them alone the harmful choice rather than the
    cautious one. Every one of those people is in a company that ORSR re-reads
    (the annual refresh lane), and the re-read produces
    `name:<x>|addr:` -- a key these rows do not have. The row is then
    unreachable for ever and the same human gets a second row and a second
    copy of the same relation, which is the split `connections.identity`
    documents. Repairing here is what keeps the table equal to what the parser
    produces.

    Two shapes, and the second is why this migration reads the way it does:

    * **13 rows** the cleaned key is free for -- a plain `UPDATE` of `address`,
      `fingerprint` and the new `birth_date`;
    * **1 row** (`id=44903`, Matej Vácha) where the cleaned key is already taken
      by `id=44904`, the same name in the same company, created 2.8 ms later
      from the *same document* -- `spolocníci` and `statutárny orgán` wrote the
      same person twice, and only one of the two says the date. There the
      source row is unreachable by construction, so it is absorbed: its
      relations move to the row the parser reaches (their role and start date
      do not clash there), its birth date fills the target's empty column, and
      the row itself goes. That absorption requires the two rows to share a
      company -- it is the module's rule 1 and nothing weaker -- so a key
      collision with a row in no shared company is held back and reported
      rather than fused.

    Absorbing is an exception to `identity.py`'s refusal to merge, and it is
    worth being exact about why. That refusal is about *heuristics over the
    wide table* -- joining same-named people on a postcode that already fuses
    places -- where a wrong merge is invisible in the product. Here the two
    rows are one company and one name, which is the module's own rule 1, on two
    rows the module's own reader would already return as one cluster; the merge
    makes storage agree with a grouping the product already shows. Nothing else
    in the schema points at a `Person`: the only foreign key into
    `connections_person` is `PersonCompanyRelation.person_id`.

    The normaliser and the fingerprint are duplicated here in full rather than
    imported from `connections.models`, for the reason 0003 gives: a migration
    must keep producing the same result after the function it would import has
    been changed.
    """
    import re
    import unicodedata
    from datetime import datetime

    Person = apps.get_model("connections", "Person")
    Relation = apps.get_model("connections", "PersonCompanyRelation")

    def strip_diacritics(text: str) -> str:
        decomposed = unicodedata.normalize("NFKD", (text or "").lower())
        return "".join(c for c in decomposed if not unicodedata.combining(c))

    def fingerprint(name: str, address: str, person_ico: str) -> str:
        if person_ico and person_ico.strip():
            return f"ico:{person_ico.strip()}"
        normalized = re.sub(r"\s+", " ", strip_diacritics(name)).strip()
        addr_part = ""
        if address:
            addr_normalized = strip_diacritics(address)
            parts = [
                p.strip()
                for p in addr_normalized.replace("\n", ",").split(",")
                if p.strip()
            ]
            for part in reversed(parts):
                if len(part) > 2 and not part.isdigit():
                    addr_part = part[:40]
                    break
        return f"name:{normalized}|addr:{addr_part}"

    def birth_component(component: str):
        """The date in a component that is the register's birth-date line."""
        if _BIRTH_STEM not in component.lower():
            return None
        match = re.search(r"(\d{2}\.\d{2}\.\d{4})", component)
        if not match:
            return None
        try:
            return datetime.strptime(match.group(1), "%d.%m.%Y").date()
        except ValueError:
            return None

    rekeyed = 0
    absorbed = 0
    relations_moved = 0
    skipped = []
    held_back = []

    rows = Person.objects.filter(address__icontains=_BIRTH_STEM).only(
        "id", "name", "address", "person_ico", "birth_date"
    )
    for person in list(rows):
        components = [c.strip() for c in (person.address or "").split(",")]
        kept, dates = [], []
        for component in components:
            if not component:
                continue
            date = birth_component(component)
            if date is None:
                kept.append(component)
            else:
                dates.append(date)

        if not dates:
            # The stem matched but no component carries a readable date. Say so
            # and leave the row whole: a half-repaired row would be worse than
            # an unrepaired one.
            skipped.append(person.id)
            continue

        cleaned = ", ".join(kept)
        target_key = fingerprint(person.name, cleaned, person.person_ico)
        target = Person.objects.filter(fingerprint=target_key).exclude(id=person.id).first()

        if target is None:
            person.address = cleaned
            person.fingerprint = target_key
            person.birth_date = dates[0]
            person.save(
                update_fields=["address", "fingerprint", "birth_date", "updated_at"]
            )
            rekeyed += 1
            continue

        source_relations = list(Relation.objects.filter(person_id=person.id))

        # Absorption is only ever the module's rule 1 -- one company, one name
        # -- so two rows that share no company are held back and reported
        # instead. `identity.py` refuses to fuse same-named people across a
        # register on a key alone, and this migration has no business being
        # less careful than the reader: a wrong fusion here is permanent and
        # invisible, where a held-back row is a duplicate somebody can count.
        if not {r.company_id for r in source_relations} & set(
            Relation.objects.filter(person_id=target.id).values_list(
                "company_id", flat=True
            )
        ):
            held_back.append(person.id)
            continue

        for relation in source_relations:
            clash = Relation.objects.filter(
                person_id=target.id,
                company_id=relation.company_id,
                role=relation.role,
                vznik_funkcie=relation.vznik_funkcie,
            ).exists()
            if clash:
                # The target already states this exact role from this exact
                # date; keeping both would be the duplicate this repair exists
                # to prevent.
                relation.delete()
            else:
                relation.person_id = target.id
                relation.save(update_fields=["person_id", "updated_at"])
                relations_moved += 1

        if dates[0] and not target.birth_date:
            target.birth_date = dates[0]
            target.save(update_fields=["birth_date", "updated_at"])

        person.delete()
        absorbed += 1

    print(
        f"    0004: {rekeyed} row(s) re-keyed to the address the reader now "
        f"produces, {absorbed} absorbed into the row it already reaches "
        f"({relations_moved} relation(s) moved)"
    )
    if skipped:
        print(f"    0004: left whole, no readable date in the line: {skipped}")
    if held_back:
        print(
            "    0004: left whole, its cleaned key is held by a row in no "
            f"shared company: {held_back}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0003_person_name_normalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Dátum narodenia"),
        ),
        migrations.RunPython(
            move_the_birth_date_out_of_the_address, migrations.RunPython.noop
        ),
    ]
