global:
  backendImage:
    tag: latest
  frontendImage:
    tag: latest
  host: cistafirma.example.com

ingress:
  host: cistafirma.example.com
  tls:
    enabled: true
    secretName: cistafirma-tls

backend:
  replicaCount: 3

frontend:
  replicaCount: 3

celery:
  worker:
    replicaCount: 2
  beat:
    replicaCount: 1

