global:
  backendImage:
    tag: latest
  frontendImage:
    tag: latest
  host: cistafirma.example.com

ingress:
  host: cistafirma.example.com
  tls:
    enabled: true
    secretName: cistafirma-tls

backend:
  replicaCount: 3

frontend:
  replicaCount: 3

celery:
  beat:
    replicaCount: 1
  workers:
    ruz:
      replicaCount: 1
    orsr:
      replicaCount: 2
    financials:
      replicaCount: 2
    insurance:
      replicaCount: 1
    default:
      replicaCount: 1

pdb:
  enabled: true
  backendMinAvailable: 2
  frontendMinAvailable: 2

