# Generated by Django 6.0.1 on 2026-02-04 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0003_alter_subscriptionplan_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, db_column='Username', max_length=150, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, db_column='Meno', max_length=100)),
                ('last_name', models.CharField(blank=True, db_column='Priezvisko', max_length=100)),
                ('is_staff', models.BooleanField(db_column='STAFF', default=False)),
                ('is_active', models.BooleanField(db_column='Aktívny', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Vytvorený')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Aktualizovaný')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('subscription_plan', models.ForeignKey(blank=True, db_column='Plán', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='subscriptions.subscriptionplan')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
